"""Fase 3.1 (painel gráfico), itens 5, 6, 7 da matriz de testes: o preço
visual (candle em formação) atualiza apenas o cache visual, nunca vira
candle persistido, nunca aciona StrategyEngine/RiskEngine/ordem/fill --
sem rede real (PAPER_LIVE via `FakeBybitTransport`).
"""
from __future__ import annotations

from sqlalchemy import func, select

from app.api.main import build_orchestrator
from app.orchestrator import Orchestrator
from app.persistence.db import session_scope
from app.persistence.models import Candle, StrategySignal
from tests.factories import activate_operational_state
from tests.fakes.bybit_fake import FakeBybitTransport
from tests.test_paper_live_mode import (
    _generate_kline_rows,
    _KlineSequenceTransport,
    make_paper_live_settings,
)


def test_get_visual_price_is_none_before_any_fetch():
    from app.market_data.bybit_provider import BybitDemoMarketDataProvider

    provider = BybitDemoMarketDataProvider(
        "https://api-demo.bybit.com", "BTCUSDT", "1",
        http_get=lambda url, params: {"result": {"list": []}},
    )
    assert provider.get_visual_price() is None


def test_visual_price_is_captured_from_the_forming_row_never_persisted_or_queued(tmp_path):
    settings = make_paper_live_settings(
        database_url=f"sqlite:///{tmp_path / 'visual_price.db'}",
        risk_max_position_usd=50.0, risk_max_total_exposure_usd=50.0,
    )
    base_transport = FakeBybitTransport()
    rows = _generate_kline_rows(n_down=10, n_up=5)
    transport = _KlineSequenceTransport(base_transport, rows)

    orch = build_orchestrator(settings, bybit_transport=transport)
    assert isinstance(orch, Orchestrator)
    activate_operational_state(orch)

    for _ in range(5):
        orch.tick()

    visual = orch.market_data_provider.get_visual_price()
    assert visual is not None
    price, at = visual
    # The fake transport's forming row is hardcoded to close=1.0 (see
    # tests/test_paper_live_mode.py::_KlineSequenceTransport) -- a value
    # that never appears among the real historical closes generated by
    # _generate_kline_rows (all >= ~85, per the price walk there).
    assert price == 1.0
    assert at is not None

    with session_scope(orch.session_factory) as session:
        # The visual price (1.0) was NEVER persisted as a closed candle.
        matching = session.execute(
            select(func.count()).select_from(Candle).where(Candle.close == 1.0)
        ).scalar()
        assert matching == 0

        # It never drove a signal either (no StrategySignal.observed_price == 1.0).
        matching_signal = session.execute(
            select(func.count()).select_from(StrategySignal).where(StrategySignal.observed_price == 1.0)
        ).scalar()
        assert matching_signal == 0

    # It never became the cursor either -- price_state (last CLOSED candle)
    # is a real historical value, never the forming-row's 1.0.
    assert orch.price_state.get("BTCUSDT") != 1.0


def test_visual_price_state_is_populated_on_the_orchestrator_even_on_no_new_candle_ticks(tmp_path):
    """The visual price cache must update even on ticks that find no new
    CLOSED candle -- proving it's captured unconditionally right after
    next_candle(), not only on the success path."""
    settings = make_paper_live_settings(
        database_url=f"sqlite:///{tmp_path / 'visual_price_no_new.db'}",
    )
    base_transport = FakeBybitTransport()
    rows = _generate_kline_rows(n_down=2, n_up=1)  # short history -> soon "no_new_candle" ticks
    transport = _KlineSequenceTransport(base_transport, rows)

    orch = build_orchestrator(settings, bybit_transport=transport)
    activate_operational_state(orch)

    saw_no_new_candle = False
    for _ in range(8):
        result = orch.tick()
        if result["status"] == "no_new_candle":
            saw_no_new_candle = True
    assert saw_no_new_candle, "fixture too short to exercise the no_new_candle path"
    assert orch.visual_price_state.get("BTCUSDT") is not None


def test_replay_provider_has_no_visual_price_and_never_breaks_the_endpoint_contract(tmp_path):
    from app.core.config import RunMode, Settings

    settings = Settings(mode=RunMode.REPLAY, symbol="BTCUSDT", database_url=f"sqlite:///{tmp_path / 'replay.db'}")
    orch = build_orchestrator(settings)
    orch.tick()
    assert getattr(orch.market_data_provider, "get_visual_price", None) is None
    assert orch.visual_price_state.get("BTCUSDT") is None  # falls back to last-closed-candle at the route layer
